### ISSUE TITLE
Aktueller Stand / Zukunft von eurem Projekt

### ISSUE THREAD

**Issue by MasterTobe** [tech4germany/rechtsinfo_api#5]
Hi @nfelger, die von euch im Rahmen von Tech4Germany geschaffene API ist wirklich toll und bietet viele Möglichkeiten den juristischen Markt mit innovativen Softwarelösungen zu bedienen. Allerdings ist mir aufgefallen, dass das Projekt seit Ende 2020 nicht mehr wirklich weiterentwickelt wurde und die Gesetzesdaten hinter der API veraltet sind. Es wäre wirklich zu schade, wenn euer Projekt nicht weitergetrieben würde. Wie sind denn eure aktuellen Pläne bzw. wird die API in der Zukunft weiterentwickelt?

Viele Grüße

**Comment by nfelger** [comment]
@MasterTobe das Tech4Germany Projekt ist abgeschlossen und die API ist sozusagen nur noch zur Projektdokumentation online. Nutzt du die API denn bzw. hast du vor sie zu nutzen? Mich würde interessieren, was dein Use-Case ist. Eventuell lässt sich eine wartungsarme Lösung finden, die Gesetze aktuell zu halten, mit der ein Grossteil des Nutzens der API verfügbar bleibt…

**Comment by MasterTobe** [comment]
@nfelger Schade. Ich hätte gerne die konsolidierten Bundesgesetze über eure API auf Änderungen hin überprüft. Das geht grds. auch mit den XML-Files über gesetze-im-internet.de, diese sind jedoch nicht wirklich gut aufbereitet. Es ist momentan noch sehr fraglich, ob ich das Projekt angehe oder nicht. Eure API setzt auch auf den XML-Files von gesetze-im-internet.de auf, oder?

**Comment by nfelger** [comment]
@MasterTobe Genau, die Daten basieren auf dem XML von Gesetze-im-Internet.

Ich habe mal etwas darüber nachgedacht, wie eine wartungsärmere Variante der API aussehen könnte. [In diesem Repo](https://github.com/nfelger/gesetze-aus-dem-internet) habe ich angefangen, eine statische Version zu bauen. Aktuell sind es nur JSON-Dumps zum herunterladen, aber wenn es meine Zeit erlaubt, hoffe ich daraus eine statische API zu bauen. 

Im Ergebnis gibt es hier wieder die tagesaktuellen Gesetzesdaten: https://nfelger.github.io/gesetze-aus-dem-internet/

**Comment by MasterTobe** [comment]
@nfelger Super 😊 Ich glaube tatsächlich, dass eine solche API für viele Entwickler eine große Hilfe wäre. Schade, dass die Gesetze über gesetze-im-internet.de nicht direkt besser aufbereitet angeboten werden...
