### ISSUE TITLE
Api has been offline since yesterday evening "ERR_TUNNEL_CONNECTION_FAILED"

### ISSUE THREAD

**Issue by lukasdeward** [tech4germany/rechtsinfo_api#9]
![Unbenannt](https://user-images.githubusercontent.com/44476930/207252662-2a54c841-65f6-4b07-b7ce-587e8577f1bb.PNG)

**Comment by nfelger** [comment]
@lukvxx The API has been shut down due to lack of funds. I've created an alternative that runs on free hosting here: https://github.com/nfelger/gesetze-aus-dem-internet (hosted at https://gadi.netlify.app/)

**Comment by lukasdeward** [comment]
@nfelger Sad to hear. I will look into hosting my own service. Thank you :)
